FROM python:3.11-slim

# 작업 디렉토리
WORKDIR /app

# 시스템 패키지
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY docker/requirements_worker.txt app/requirements_worker.txt

RUN pip install --no-cache-dir -r app/requirements_worker.txt

# 애플리케이션 코드 복사
COPY scripts/ /app

# 실행 명령
CMD ["python", "-u", "pipeline_worker.py"]
