FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*

COPY docker/requirements_fastapi.txt /app/requirements_fastapi.txt
RUN pip install --no-cache-dir -r /app/requirements_fastapi.txt

COPY . /app

EXPOSE 8000

CMD ["gunicorn", "api.main:app", "--workers", "3", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "--access-logfile", "-", "--error-logfile", "-", "--log-level", "info"]
